Ventas/Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ventas.Models;
using Ventas.ViewModels;

namespace Ventas.Controllers
{
    public class EmpleadosController : Controller
    {
        VentasDbContext _context = new VentasDbContext();

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult Lista()
        {
            var lista = _context.Empleados.ToList();

            return View(lista);
        }

        public ActionResult Nuevo()
        {
            var empleadoVacio = new EmpleadoViewModel();

            return View("Empleado", empleadoVacio);
        }

        public ActionResult Actualizar(int id)
        {
            var empleado = _context.Empleados.FirstOrDefault(x => x.Id == id);

            if (empleado == null)
                return null;

            var empleadoVM = new EmpleadoViewModel
            {
                Id = empleado.Id,
                Apellido = empleado.Apellido,
                Nombre = empleado.Nombre,
                DNI = empleado.DNI,
                FecNac = empleado.FecNac,
                Legajo = empleado.Legajo
            };

            return View("Empleado", empleadoVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Guardar(EmpleadoViewModel empleadoVM)
        {
            if (!ModelState.IsValid)
            {
                if (empleadoVM.Id == null)
                    return RedirectToAction("Nuevo");
                else
                    return RedirectToAction("Actualizar", new { id = empleadoVM.Id });
            }
                

            if (empleadoVM.Id == null)
            {
                var empleado = new Empleados()
                {
                    Apellido = empleadoVM.Apellido,
                    Nombre = empleadoVM.Nombre,
                    DNI = empleadoVM.DNI,
                    FecNac = empleadoVM.FecNac,
                    Legajo = empleadoVM.Legajo
                };

                _context.Empleados.Add(empleado);
            }
            else
            {
                var empleadoEnDb = _context.Empleados.FirstOrDefault(x => x.Id == empleadoVM.Id);
                empleadoEnDb.Nombre = empleadoVM.Nombre;
                empleadoEnDb.Apellido = empleadoVM.Apellido;
                empleadoEnDb.DNI = empleadoVM.DNI;
                empleadoEnDb.FecNac = empleadoVM.FecNac;
            }

            _context.SaveChanges();

            return RedirectToAction("Lista");
        }

        public ActionResult Borrar(int id)
        {
            var empleado = _context.Empleados.FirstOrDefault(x => x.Id == id);

            if (empleado == null)
                return RedirectToAction("Lista");

            try
            {
                _context.Empleados.Remove(empleado);
                _context.SaveChanges();
            }
            catch (DbUpdateException ex)
            {
                ViewBag.Error = "Empleado ya asociado a una venta. Elimine la factura para proceder.";
            }

            var lista = _context.Empleados.ToList();
            return View("Lista", lista);
        }
    }
}

Ventas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ventas", "Lista", "Ventas")</li>
                    <li>@Html.ActionLink("Emplados", "Lista", "Empleados")</li>
                    <li>@Html.ActionLink("Clientes", "Lista", "Clientes")</li>
                    <li>@Html.ActionLink("Productos", "Lista", "Productos")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Ventas/Views/Shared/_LayoutImp.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reporte</title>
    <script>
        window.onload = function () { window.print(); }
    </script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        body {
            background-color: white;
            max-width: 750px;
            margin-left: auto;
            margin-right: auto;
            margin-top: 40px;
            font-size: 12px;
        }

        .row {
            margin-left: 0px;
            margin-right: 0px;
        }

        h1 {
            font-size: 1.4rem;
        }

        h2 {
            font-size: 1.1rem;
        }

        .dato {
            font-weight: bold;
        }
    </style>
</head>
<body class="border border-dark">
    <div class="p-3">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>